sudo: false
language: ruby
rvm:
- 2.3.1
- 2.4.0
branches:
  only:
  - master
script: bundle exec rspec spec
notifications:
  slack:
    secure: sdIcxKDt3X7Jm2KvAwUqXPm29KDK5s4z5Cmk9xIakWkgGAtkZ6ipaXpYMS5SXIff290hXEycO4HbAm4P5KMocqrPDN4Z56Gc88uFL7J74Wja+CQXkAZ/KK4PkiYb67y5/eQhvO/UQG0LFlxvy8BIdOTZpjkeWt6R111ZKhnjN1lRqnFd2JavML1EWAqh+zYviyFfoPi3TgcvDD/v+DfK3ujrymnSL/FDrvAaYmn16DZ3eSk8R0Uj1n4xkKjOAJ2aCNTRQ2IVSryOZrPP19qZn2HwIvkK1ktYxaClau9MZC+GOsbuYKjmMSemkYiC5wkIa5Arzfi1vWZ/kOhB2paUL2J6AEeaonUrbhG1RmFOPluQLrKviCzegmEdcQmUYYke1EBSsbKnbeFJk8E/mOzkA4Wo2nmN7ZmCx4WAvmSr7OZgBc23OWb0TjIJqwH+PO0AYwHFJ1vKKPG5/BMusMlofSdE/7vFW5c1ePF8aw6BSiGUZOAxA7XkBUpjLaARZGx1BJvaBrOt4oNki5lJsdbii+HPXNaMcz47QebURyfoZx35Y21qYcw6BpGdsKLemOMI8SujdDtrbe0KZ/60p1fEj9+76zBKSXBIBDib8ifA2hX0KDaY5Z+RuBrRpu9JP8+hsVPcI/0GznF7NFrISe+znr4OlZO53rDdCmoNOxiSd08=
